Script started on Wed 29 Aug 2018 01:15:28 PM MDT
]0;jagmjg@jagmjg-VirtualBox: ~/cse113/exercise[01;32mjagmjg@jagmjg-VirtualBox[00m:[01;34m~/cse113/exercise[00m$ gcc name.c -o name
]0;jagmjg@jagmjg-VirtualBox: ~/cse113/exercise[01;32mjagmjg@jagmjg-VirtualBox[00m:[01;34m~/cse113/exercise[00m$ ./name













JJJJJJJJJJJJJJJJJ
        J
        J                                        
        J                              0                      n    nnnnnnnnn
        J                        l                            n  n          n
        J                        l            @@@@@@          n n             n
        J        U          U    l     i    @        @        n                n
        J        U          U    l     i  @            @@     n                n
        J        U          U    l     i  @            @ @    n                n
 J     J         U          U    l     i  @            @ @    n                n
 J    J           U        U     l     i    @        @    @   n                n
  JJJ               UUUUUU       l     i      aaaaaa       @  n                n
]0;jagmjg@jagmjg-VirtualBox: ~/cse113/exercise[01;32mjagmjg@jagmjg-VirtualBox[00m:[01;34m~/cse113/exercise[00m$ exit
exit

Script done on Wed 29 Aug 2018 01:15:48 PM MDT
