Julian Garcia
Lab2
September 19th 2018
Script started on Wed 19 Sep 2018 10:27:32 AM MDT
]0;jagmjg@jagmjg-VirtualBox: ~/cse113/lab2[01;32mjagmjg@jagmjg-VirtualBox[00m:[01;34m~/cse113/lab2[00m$ exit./lab2gcc -g -Wall lab2.c -lm -o lab2
]0;jagmjg@jagmjg-VirtualBox: ~/cse113/lab2[01;32mjagmjg@jagmjg-VirtualBox[00m:[01;34m~/cse113/lab2[00m$ gcc -g -Wall lab2.c -lm -o lab2exit[K./lab2

!!!!!!!!!!!!!!!!!!!!!WELCOME TO MY MATH CAVE!!!!!!!!!!!!!!!!!!!!

Indicate which type of operation you wish to perform
P regular polygon operations
T for triangle operations
C for circle operations
R for rectangle operations
p
----------------- Regular Polygon Calculations ------------------
Indicate the operation you want to perform
A for the area
I for the interior angle
E for the exterior angle
a

For the area of a regular polygon----------------------

Enter the number of sides of the regular polygon (interger)
4
Enter the size of one side of the regular polygon
4
The area of a regular polygon 4 sides of 4.000000 length is 16.000003
-------------------------------------------------------
]0;jagmjg@jagmjg-VirtualBox: ~/cse113/lab2[01;32mjagmjg@jagmjg-VirtualBox[00m:[01;34m~/cse113/lab2[00m$ ./lab2

!!!!!!!!!!!!!!!!!!!!!WELCOME TO MY MATH CAVE!!!!!!!!!!!!!!!!!!!!

Indicate which type of operation you wish to perform
P regular polygon operations
T for triangle operations
C for circle operations
R for rectangle operations
p
----------------- Regular Polygon Calculations ------------------
Indicate the operation you want to perform
A for the area
I for the interior angle
E for the exterior angle
i


For the interior angle of a regular polygon------------

Enter the number of sides (interger) of the polygon
4

The interior angle of a regular polygon with 4 sides is 90.000000
-------------------------------------------------------
]0;jagmjg@jagmjg-VirtualBox: ~/cse113/lab2[01;32mjagmjg@jagmjg-VirtualBox[00m:[01;34m~/cse113/lab2[00m$ ./lab2

!!!!!!!!!!!!!!!!!!!!!WELCOME TO MY MATH CAVE!!!!!!!!!!!!!!!!!!!!

Indicate which type of operation you wish to perform
P regular polygon operations
T for triangle operations
C for circle operations
R for rectangle operations
p
----------------- Regular Polygon Calculations ------------------
Indicate the operation you want to perform
A for the area
I for the interior angle
E for the exterior angle
e

For the exterior angle of a regular polygon------------

Enter the number of sides(int) of the polygon
4
The eterior angle of a regular polygon with 4 sides is 90.000000

----------------------------------------------------------------
]0;jagmjg@jagmjg-VirtualBox: ~/cse113/lab2[01;32mjagmjg@jagmjg-VirtualBox[00m:[01;34m~/cse113/lab2[00m$ ./lab2

!!!!!!!!!!!!!!!!!!!!!WELCOME TO MY MATH CAVE!!!!!!!!!!!!!!!!!!!!

Indicate which type of operation you wish to perform
P regular polygon operations
T for triangle operations
C for circle operations
R for rectangle operations
t

-------------------- Triangle Calculations ----------------------

Indicate the operation you want to perform
P for the perimeter
H for the hypotenuse
A for the area

p

For the perimeter of a triangle-----------------------

Enter the height of the triangle
4
Enter the base of the triangle
3
The perimeter of a triangle with 4.000000 height and 3.000000 base is 12.000000
------------------------------------------------------
]0;jagmjg@jagmjg-VirtualBox: ~/cse113/lab2[01;32mjagmjg@jagmjg-VirtualBox[00m:[01;34m~/cse113/lab2[00m$ ./lab2

!!!!!!!!!!!!!!!!!!!!!WELCOME TO MY MATH CAVE!!!!!!!!!!!!!!!!!!!!

Indicate which type of operation you wish to perform
P regular polygon operations
T for triangle operations
C for circle operations
R for rectangle operations
t

-------------------- Triangle Calculations ----------------------

Indicate the operation you want to perform
P for the perimeter
H for the hypotenuse
A for the area

h

For the hypotenuse of a triangle-------------------

Enter the height of the triangle:
3
Enter the base of the triangle
2
The hypotenuse of a triangle with 3.000000 height and 2.000000 base is 3.605551
---------------------------------------------------
]0;jagmjg@jagmjg-VirtualBox: ~/cse113/lab2[01;32mjagmjg@jagmjg-VirtualBox[00m:[01;34m~/cse113/lab2[00m$ ./lab2

!!!!!!!!!!!!!!!!!!!!!WELCOME TO MY MATH CAVE!!!!!!!!!!!!!!!!!!!!

Indicate which type of operation you wish to perform
P regular polygon operations
T for triangle operations
C for circle operations
R for rectangle operations
t

-------------------- Triangle Calculations ----------------------

Indicate the operation you want to perform
P for the perimeter
H for the hypotenuse
A for the area

a

For the area of a triangle-------------------------

Enter the height of the triangle:
4
Enter the size of the base:
3
The area of a triangle with 4.000000 height and 3.000000 base is 6.000000

-----------------------------------------------------------------
]0;jagmjg@jagmjg-VirtualBox: ~/cse113/lab2[01;32mjagmjg@jagmjg-VirtualBox[00m:[01;34m~/cse113/lab2[00m$ ./lab2

!!!!!!!!!!!!!!!!!!!!!WELCOME TO MY MATH CAVE!!!!!!!!!!!!!!!!!!!!

Indicate which type of operation you wish to perform
P regular polygon operations
T for triangle operations
C for circle operations
R for rectangle operations
c

------------------------ Circle Calculations --------------------
Indicate the calculation you want
C for circumference
A for area

c

For the circumference of a circle------------------

Enter the radius of the circle:
4
The circumference of a circle with 4.000000 radius is 25.132744
---------------------------------------------------
]0;jagmjg@jagmjg-VirtualBox: ~/cse113/lab2[01;32mjagmjg@jagmjg-VirtualBox[00m:[01;34m~/cse113/lab2[00m$ ./lab2

!!!!!!!!!!!!!!!!!!!!!WELCOME TO MY MATH CAVE!!!!!!!!!!!!!!!!!!!!

Indicate which type of operation you wish to perform
P regular polygon operations
T for triangle operations
C for circle operations
R for rectangle operations
c

------------------------ Circle Calculations --------------------
Indicate the calculation you want
C for circumference
A for area

a

For the area of a circle---------------------------

Enter the radius of the circle:
4
The area of a circle with radius 4.000000 is 50.265488

-----------------------------------------------------------------
]0;jagmjg@jagmjg-VirtualBox: ~/cse113/lab2[01;32mjagmjg@jagmjg-VirtualBox[00m:[01;34m~/cse113/lab2[00m$ ./lab2

!!!!!!!!!!!!!!!!!!!!!WELCOME TO MY MATH CAVE!!!!!!!!!!!!!!!!!!!!

Indicate which type of operation you wish to perform
P regular polygon operations
T for triangle operations
C for circle operations
R for rectangle operations
r

-------------------- Rectangle Calculations ---------------------
Indicate the calculation you want to perform
D for diagonal
P for perimeter
A for area

d

For the diagonal of a rectangle--------------------

Enter the length of the rectangle:
4
Enter the width of the rectangle
4
The diagonal of a rectangle of 4.000000 width and 4.000000 length is 5.656854
---------------------------------------------------
]0;jagmjg@jagmjg-VirtualBox: ~/cse113/lab2[01;32mjagmjg@jagmjg-VirtualBox[00m:[01;34m~/cse113/lab2[00m$ ./lab2

!!!!!!!!!!!!!!!!!!!!!WELCOME TO MY MATH CAVE!!!!!!!!!!!!!!!!!!!!

Indicate which type of operation you wish to perform
P regular polygon operations
T for triangle operations
C for circle operations
R for rectangle operations
r

-------------------- Rectangle Calculations ---------------------
Indicate the calculation you want to perform
D for diagonal
P for perimeter
A for area

p

For the perimeter of a rectangle-------------------

Enter the length of the rectangle:
3
Enter the width of the rectangle:
3
The perimeter of a rectangle of 3.000000 length and 3.000000 width is 12.000000
----------------------------------------------------
]0;jagmjg@jagmjg-VirtualBox: ~/cse113/lab2[01;32mjagmjg@jagmjg-VirtualBox[00m:[01;34m~/cse113/lab2[00m$ ./lab2

!!!!!!!!!!!!!!!!!!!!!WELCOME TO MY MATH CAVE!!!!!!!!!!!!!!!!!!!!

Indicate which type of operation you wish to perform
P regular polygon operations
T for triangle operations
C for circle operations
R for rectangle operations
r

-------------------- Rectangle Calculations ---------------------
Indicate the calculation you want to perform
D for diagonal
P for perimeter
A for area

a

For the area of a rectangle-------------------------

Enter the length of the rectangle:
4
Enter the width of the rectangle:
6
The area of a rectangle of 4.000000 lenght and 6.000000 with is 24.000000

-----------------------------------------------------------------

]0;jagmjg@jagmjg-VirtualBox: ~/cse113/lab2[01;32mjagmjg@jagmjg-VirtualBox[00m:[01;34m~/cse113/lab2[00m$ ./lab2

!!!!!!!!!!!!!!!!!!!!!WELCOME TO MY MATH CAVE!!!!!!!!!!!!!!!!!!!!

Indicate which type of operation you wish to perform
P regular polygon operations
T for triangle operations
C for circle operations
R for rectangle operations
r

-------------------- Rectangle Calculations ---------------------
Indicate the calculation you want to perform
D for diagonal
P for perimeter
A for area

a

For the area of a rectangle-------------------------

Enter the length of the rectangle:
-3
Enter the width of the rectangle:
-4
Error: Length and width cannot be negative
(•_•)
( •_•)>⌐■-■
(⌐■_■)
Later nerd

]0;jagmjg@jagmjg-VirtualBox: ~/cse113/lab2[01;32mjagmjg@jagmjg-VirtualBox[00m:[01;34m~/cse113/lab2[00m$ exit
exit

Script done on Wed 19 Sep 2018 10:29:27 AM MDT
