Julian Garcia
10/22/18
Lab5
Script started on Mon 22 Oct 2018 11:28:53 PM MDT
]0;jagmjg@jagmjg-VirtualBox: ~/cse113/lab5[01;32mjagmjg@jagmjg-VirtualBox[00m:[01;34m~/cse113/lab5[00m$ ./sundays
Number of sundays between 1901 and 2000 is 5436
]0;jagmjg@jagmjg-VirtualBox: ~/cse113/lab5[01;32mjagmjg@jagmjg-VirtualBox[00m:[01;34m~/cse113/lab5[00m$ exu[Kit
exit

Script done on Mon 22 Oct 2018 11:29:01 PM MDT
