Julian Garcia
Lab 7
11/4/2018
Script started on Sun 11 Nov 2018 05:09:08 PM MDT
]0;jagmjg@jagmjg-VirtualBox: ~/cse113/lab7[01;32mjagmjg@jagmjg-VirtualBox[00m:[01;34m~/cse113/lab7[00m$ exitquitvalgrind --leak-check=yes ./dynamic
==14069== Memcheck, a memory error detector
==14069== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==14069== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==14069== Command: ./dynamic
==14069==
u = "c run, c run unix, run unix run"
u = "c run, c run unix, run unix run, go c, go!"
==14069==
==14069== HEAP SUMMARY:
==14069==     in use at exit: 0 bytes in 0 blocks
==14069==   total heap usage: 2 allocs, 2 frees, 1,067 bytes allocated
==14069==
==14069== All heap blocks were freed -- no leaks are possible
==14069==
==14069== For counts of detected and suppressed errors, rerun with: -v
==14069== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
]0;jagmjg@jagmjg-VirtualBox: ~/cse113/lab7[01;32mjagmjg@jagmjg-VirtualBox[00m:[01;34m~/cse113/lab7[00m$ exit
exit

Script done on Sun 11 Nov 2018 05:09:19 PM MDT
