Julian Garcia
11/4/2018
Lab7
Script started on Sun 11 Nov 2018 05:11:08 PM MDT
]0;jagmjg@jagmjg-VirtualBox: ~/cse113/lab7[01;32mjagmjg@jagmjg-VirtualBox[00m:[01;34m~/cse113/lab7[00m$ ./gyn[K[K[Kdynam[K[K[K[K[K[K[Kexitvalgrind --leak-check=yes ./dynamic
==14135== Memcheck, a memory error detector
==14135== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==14135== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==14135== Command: ./dynamic
==14135==
u = "c run, c run unix, run unix run"
u = "c run, c run unix, run unix run, go c, go!"
==14135==
==14135== HEAP SUMMARY:
==14135==     in use at exit: 43 bytes in 1 blocks
==14135==   total heap usage: 2 allocs, 1 frees, 1,067 bytes allocated
==14135==
==14135== 43 bytes in 1 blocks are definitely lost in loss record 1 of 1
==14135==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14135==    by 0x400720: main (dynamic_strings.c:19)
==14135==
==14135== LEAK SUMMARY:
==14135==    definitely lost: 43 bytes in 1 blocks
==14135==    indirectly lost: 0 bytes in 0 blocks
==14135==      possibly lost: 0 bytes in 0 blocks
==14135==    still reachable: 0 bytes in 0 blocks
==14135==         suppressed: 0 bytes in 0 blocks
==14135==
==14135== For counts of detected and suppressed errors, rerun with: -v
==14135== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
]0;jagmjg@jagmjg-VirtualBox: ~/cse113/lab7[01;32mjagmjg@jagmjg-VirtualBox[00m:[01;34m~/cse113/lab7[00m$ exit
exit

Script done on Sun 11 Nov 2018 05:11:32 PM MDT
